# Health Stats Part 4: Pandas DataFrames

<!--- Paste in your explanation from part 1.  --->

The Waist-hip ratio or waist-to-hip ratio (WHR) is the dimensionless ratio of the circumference of the waist to that of the hips. This is calculated as waist measurement divided by hip measurement (W รท H).
Divide the first number by the second to get your waist-to-hip ratio (WHR). For women, if your WHR is 0.80 or less, you are a "pear." If your WHR is greater than 0.80, you are an "apple." For men, a WHR of greater than 0.90 means you are an apple and at increased heart risk too.

## Source Data

<!--- Paste in your data definition table from part 2. --->

* ID Column Type Int
* Waist (measurement of waist size) Column Type Int
* Hip (measurement of hip size) Column Type Int
* Gender Column Type Str

## Data Import

In [70]:
# Goal: Extract the data from the file
import numpy as np
import pandas as pd

df = pd.read_csv('w2h_data.csv',dtype={0:'int',1:'float',2:'float',3:'str'})
df.set_index('ID', inplace = True)

df

    Waist   Hip Gender
ID
1    30.0  32.0      M
2    32.0  37.0      M
3    30.0  36.0      M
4    33.0  39.0      M
5    29.0  33.0      M
6    32.0  38.0      M
7    33.0  42.0      M
8    30.0  40.0      M
9    30.0  37.0      M
10   32.0  39.0      M
11   24.0  35.0      F
12   25.0  37.0      F
13   24.0  37.0      F
14   22.0  34.0      F
15   26.0  38.0      F
16   26.0  37.0      F
17   25.0  38.0      F
18   26.0  37.0      F
19   28.0  40.0      F
20   23.0  35.0      F

## Calculations

In [72]:
male_apples = np.logical_and((df['Waist']/df['Hip'] >0.9),df['Gender'] == 'M' )
female_apples = np.logical_and((df['Waist']/df['Hip']>=0.8),np.logical_not(df['Gender'] == 'M'))
apples= np.logical_or(male_apples,female_apples)

df['Shape'] = np.where(apples,'Apple', 'Pear')

df

    Waist   Hip Gender  Shape
ID
1    30.0  32.0      M  Apple
2    32.0  37.0      M   Pear
3    30.0  36.0      M   Pear
4    33.0  39.0      M   Pear
5    29.0  33.0      M   Pear
6    32.0  38.0      M   Pear
7    33.0  42.0      M   Pear
8    30.0  40.0      M   Pear
9    30.0  37.0      M   Pear
10   32.0  39.0      M   Pear
11   24.0  35.0      F   Pear
12   25.0  37.0      F   Pear
13   24.0  37.0      F   Pear
14   22.0  34.0      F   Pear
15   26.0  38.0      F   Pear
16   26.0  37.0      F   Pear
17   25.0  38.0      F   Pear
18   26.0  37.0      F   Pear
19   28.0  40.0      F   Pear
20   23.0  35.0      F   Pear

## Output

In [82]:
# Goal: pretty print the rows as an HTML table

display(df)

# Export to "StatsResults.csv"
df.to_csv("StatsResults.csv")

    Waist   Hip Gender  Shape
ID
1    30.0  32.0      M  Apple
2    32.0  37.0      M   Pear
3    30.0  36.0      M   Pear
4    33.0  39.0      M   Pear
5    29.0  33.0      M   Pear
6    32.0  38.0      M   Pear
7    33.0  42.0      M   Pear
8    30.0  40.0      M   Pear
9    30.0  37.0      M   Pear
10   32.0  39.0      M   Pear
11   24.0  35.0      F   Pear
12   25.0  37.0      F   Pear
13   24.0  37.0      F   Pear
14   22.0  34.0      F   Pear
15   26.0  38.0      F   Pear
16   26.0  37.0      F   Pear
17   25.0  38.0      F   Pear
18   26.0  37.0      F   Pear
19   28.0  40.0      F   Pear
20   23.0  35.0      F   Pear